//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSplitTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileSplitTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Barcode format.
        /// </summary>
        internal static string MSG_BARCODE_INVALID {
            get {
                return ResourceManager.GetString("MSG_BARCODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Can format.
        /// </summary>
        internal static string MSG_CAN_INVALID {
            get {
                return ResourceManager.GetString("MSG_CAN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not export file.
        /// </summary>
        internal static string MSG_CAN_NOT_EXPORT_FILE {
            get {
                return ResourceManager.GetString("MSG_CAN_NOT_EXPORT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Card Horder Name format.
        /// </summary>
        internal static string MSG_CARD_HORDER_NAME_INVALID {
            get {
                return ResourceManager.GetString("MSG_CARD_HORDER_NAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Card Number format.
        /// </summary>
        internal static string MSG_CARD_NUMBER_01_INVALID {
            get {
                return ResourceManager.GetString("MSG_CARD_NUMBER_01_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect CardNumber format.
        /// </summary>
        internal static string MSG_CARD_NUMBER_02_INVALID {
            get {
                return ResourceManager.GetString("MSG_CARD_NUMBER_02_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Card Number of Back Side format.
        /// </summary>
        internal static string MSG_CARD_NUMBER_BACK_SIDE_INVALID {
            get {
                return ResourceManager.GetString("MSG_CARD_NUMBER_BACK_SIDE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect CardID format.
        /// </summary>
        internal static string MSG_CARDID_INVALID {
            get {
                return ResourceManager.GetString("MSG_CARDID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Company Name format.
        /// </summary>
        internal static string MSG_COMPANY_NAME_INVALID {
            get {
                return ResourceManager.GetString("MSG_COMPANY_NAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect CVV2 format.
        /// </summary>
        internal static string MSG_CVV2_INVALID {
            get {
                return ResourceManager.GetString("MSG_CVV2_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Effective Date format.
        /// </summary>
        internal static string MSG_EFFECTIVE_DATE_INVALID {
            get {
                return ResourceManager.GetString("MSG_EFFECTIVE_DATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Expiry Date format.
        /// </summary>
        internal static string MSG_EXPIRY_DATE_INVALID {
            get {
                return ResourceManager.GetString("MSG_EXPIRY_DATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export file successfully.
        /// </summary>
        internal static string MSG_EXPORT_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_EXPORT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Fix format.
        /// </summary>
        internal static string MSG_FIX_INVALID {
            get {
                return ResourceManager.GetString("MSG_FIX_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect iCCV format.
        /// </summary>
        internal static string MSG_ICCV_INVALID {
            get {
                return ResourceManager.GetString("MSG_ICCV_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file content.
        /// </summary>
        internal static string MSG_INVALID_FILE_CONTENT {
            get {
                return ResourceManager.GetString("MSG_INVALID_FILE_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect MagTrack1 format.
        /// </summary>
        internal static string MSG_MAG_TRACK_1_INVALID {
            get {
                return ResourceManager.GetString("MSG_MAG_TRACK_1_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect MagTrack2 format.
        /// </summary>
        internal static string MSG_MAG_TRACK_2_INVALID {
            get {
                return ResourceManager.GetString("MSG_MAG_TRACK_2_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge file successfully.
        /// </summary>
        internal static string MSG_MERGE_FILE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_MERGE_FILE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect PAN format.
        /// </summary>
        internal static string MSG_PAN_INVALID {
            get {
                return ResourceManager.GetString("MSG_PAN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Pan Sequence Number format.
        /// </summary>
        internal static string MSG_PAN_SEQUENCE_INVALID {
            get {
                return ResourceManager.GetString("MSG_PAN_SEQUENCE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Production Code format.
        /// </summary>
        internal static string MSG_PRODUCTION_CODE_INVALID {
            get {
                return ResourceManager.GetString("MSG_PRODUCTION_CODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Record Number format.
        /// </summary>
        internal static string MSG_RECORD_NUMBER_INVALID {
            get {
                return ResourceManager.GetString("MSG_RECORD_NUMBER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect ServiceCode format.
        /// </summary>
        internal static string MSG_SERVICE_CODE_INVALID {
            get {
                return ResourceManager.GetString("MSG_SERVICE_CODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MSG_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SUCCESS", resourceCulture);
            }
        }
    }
}
